# Generated by Django 4.2.1 on 2023-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0003_alter_driver_dob_alter_driver_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
